### ISSUE TITLE
CSS code for today's events

### ISSUE THREAD

**Issue by user8446** [cardi/google-calendar-minimal-dark#1]
Hello,

Thank you for this.

I am trying to colorize and highlight the background color in the "today" calendar block. Would you happen to know the code to add that to the style.css?

**Comment by cardi** [comment]
It looks like the "today" label is highlighted using the class `F262Ye` in either an `h2` or `div` element.

If you're trying to highlight the entire cell or column (e.g., on Month or Week views), I don't see any obvious classes that indicate that it's "today".

Perhaps it might be possible if you modify the parent container of an element that contains `F262Ye`—that might require some additional functions to [contentscript-end.js](https://github.com/cardi/google-calendar-minimal-dark/blob/4aa661863bc581849940c2eff316a475f9b19317/contentscript-end.js).

**Comment by user8446** [comment]
Thank you for pointing me in the right direction, I will look into it!
